### PR TITLE
Terminal APIs (work-in-progress)

### PR DESCRIPTION
**Pull request by gtritchie**
Here's currently planned set of terminal APIs. I've got these implemented on the client, with some issues still being ironed out so not ready to have this merged yet.

Client side: https://github.com/rstudio/rstudio/pull/1176

### CODE REVIEW

**Comment by gtritchie** [comment]
Done all planned APIs for terminal.

**Comment by hadley** [comment]
I think you should consider a common prefix to make autocomplete more natural.

**Comment by gtritchie** [comment]
Good point. Any suggested "typical" R naming convention for this?

**Comment by kevinushey** [comment]
Maybe use `terminal` as a prefix? So that the function names are e.g.

```
terminalCreate()
terminalClear()
terminalList()
...
```

**Comment by gtritchie** [comment]
Another angle, you can access the terminal APIs without the rstudioapi package, via:

.Options$terminal_manager$....

Then you get the whole set in the dropdown, making it easier to see what APIs exist.

I assume the rstudioapi package is our officially supported way to exposing APIs, so I will go ahead and name them all with a consistent prefix in there (and change the internal set to match).

**Comment by jjallaire** [comment]
Yes, the options is just there so that packages that need to have very few
dependencies can call the terminal APIs w/o depending on rstudioapi

**Comment by gtritchie** [comment]
Ok, I've renamed them all to start with terminal:

activateTerminal -> terminalActivate
clearTerminal -> terminalClear
createTerminal -> terminalCreate
getAllTerminals -> terminalList
getTerminalBuffer -> terminalBuffer
getTerminalContext -> terminalContext
getVisibleTerminal -> terminalVisible
isTerminalBusy -> terminalBusy
isTerminalRunning -> terminalRunning
killTerminal -> terminalKill
sendToTerminal -> terminalSend

**Comment by kevinushey** [comment]
Thoughts for `terminalCreate()`:

- Allow it to accept a command to execute
- Allow it to accept a working directory to launch in (defaulting to project directory)

**Comment by gtritchie** [comment]
@kevinushey, I'll look at adding that to `terminalCreate()`; you could do that via `terminalSend()` after `terminalCreate()` but can see where it would be nice to have it as a single operation.

**Comment by kevinushey** [comment]
Chatting with @jjallaire, I think our intention here was really for executing commands in a terminal non-interactively -- ie, to create a terminal, run a command, and then close the terminal session (but leave the terminal tab output visible; just detached from the underlying terminal session).

@jjallaire: can you confirm if that sounds right?

**Comment by hadley** [comment]
Is this instead of running in the build pane or as well as?

**Comment by kevinushey** [comment]
This is instead of running in the build pane. Note that we only show the Build pane in 'Package' configurations (e.g. R package, R website, custom Makefile), and for those situations we want a separate mechanism that allows a package to take over the Build pane (defining UI + actions that can be taken).

This particular interface would be much simpler -- just a mechanism for running arbitrary shell commands outside of the R process, hooked up to a terminal.

**Comment by gtritchie** [comment]
Having a terminal pane not close when it's underlying process exits is very doable. Probably behavior gated by a flag passed to `terminalCreate()`. Could also be a user-option for interactive terminals if that's useful in general.

**Comment by jjallaire** [comment]
Also, if we have you run in the Build pane we block all other access to the
build pane. For example, if you want to run a long running test or revdep
check operation you wouldn't be able to document, build and reload, test,
etc. until it was finished if we took over the Build pane.

**Comment by hadley** [comment]
Agreed. The advantage of the build pane is that you can see both the console and the build pane.

**Comment by gtritchie** [comment]
Going to send a clean PR now that APIs are what they will be for 1.1.

**Pull request closed without merging**
