### PR TITLE
Switch to GitHub Actions for package checks and pkgdown

### PR DESCRIPTION
**Pull request by jennybc**
This is the standard tidyverse / r-lib GHA treatment.

If this has some fallout or needs some tweaking, I'm happy to help see it through.

### CODE REVIEW

**Comment by kevinushey** [comment]
LGTM!

The website is currently built off of the `gh-pages` branch -- does that effect anything in this PR re: pkgdown?

**Comment by jennybc** [comment]
The last successful build + deploy via Travis was in October 2020, so something clearly is broken there. Basically, this PR isn't going to make that worse 😅

Yeah, this PR includes a workflow that should start handling pkgdown build + deploy as well.
Once you merge, we'll be able to confirm that it's working.

**Comment by jennybc** [comment]
The github-pages branch is now updating again:

https://github.com/rstudio/rstudioapi/commits/gh-pages

 Do the site look the way you expect?

**Comment by jennybc** [comment]
This looks promising
Screen Shot 2021-05-26 at 4 30 49 PM

**Pull request merged**
